"""Serialise a :class:`~g4beamline2bdsim.model.BdsimModel` to GMAD text."""

from __future__ import annotations

from typing import Any, List

from .model import BdsimModel, Element


def _format_value(value: Any) -> str:
    """Render a parameter value as GMAD source."""
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int,)):
        return str(value)
    if isinstance(value, float):
        return _format_number(value)
    if isinstance(value, tuple) and len(value) == 2:
        number, unit = value
        return f"{_format_number(number)}*{unit}"
    if isinstance(value, str):
        # Already-quoted strings are passed through; otherwise quote it.
        if value.startswith('"') and value.endswith('"'):
            return value
        return f'"{value}"'
    return str(value)


def _format_number(number: float) -> str:
    if isinstance(number, int) or (isinstance(number, float) and number.is_integer()):
        # Keep small integers tidy but avoid 1e16 turning into a huge string.
        if abs(number) < 1e15:
            return str(int(number))
    # General-format with enough precision, trimming trailing zeros.
    text = f"{number:.10g}"
    return text


class GmadWriter:
    """Write a :class:`BdsimModel` to a GMAD string or file."""

    def __init__(self, model: BdsimModel, line_width: int = 88) -> None:
        self.model = model
        self.line_width = line_width

    # -- public API ---------------------------------------------------------
    def to_string(self) -> str:
        parts: List[str] = []
        parts.append(self._header())
        if self.model.warnings:
            parts.append(self._warnings_block())
        parts.append(self._elements_block())
        parts.append(self._line_block())
        parts.append(self._beam_block())
        parts.append(self._options_block())
        sampler_block = self._samplers_block()
        if sampler_block:
            parts.append(sampler_block)
        return "\n\n".join(p for p in parts if p).rstrip() + "\n"

    def write(self, path: str) -> None:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(self.to_string())

    # -- blocks -------------------------------------------------------------
    def _header(self) -> str:
        lines = [
            "! ======================================================================",
            "! BDSIM (GMAD) model generated by g4beamline2bdsim",
            "! ======================================================================",
        ]
        for comment in self.model.header_comments:
            lines.append(f"! {comment}")
        return "\n".join(lines)

    def _warnings_block(self) -> str:
        lines = ["! ---- conversion warnings ----"]
        for w in self.model.warnings:
            lines.append(f"! WARNING: {w}")
        return "\n".join(lines)

    def _elements_block(self) -> str:
        lines = ["! ---- element definitions ----"]
        for element in self.model.elements:
            lines.append(self._format_element(element))
        return "\n".join(lines)

    def _format_element(self, element: Element) -> str:
        prefix = f"{element.name}: {element.type}"
        items = [f"{k}={_format_value(v)}" for k, v in element.params.items()]
        comment = f"  ! {element.comment}" if element.comment else ""
        if not items:
            return prefix + ";" + comment
        one_line = prefix + ", " + ", ".join(items) + ";"
        if len(one_line) <= self.line_width and not comment:
            return one_line
        # Multi-line form: each parameter on its own continuation line.
        indent = " " * (len(element.name) + 2)
        body = (",\n" + indent).join(items)
        return f"{prefix}, {body};" + comment

    def _line_block(self) -> str:
        name = self.model.line_name
        if not self.model.line:
            return f"! ---- beamline ----\n{name}: line=();\nuse, {name};"
        lines = ["! ---- beamline ----"]
        # Wrap the line definition across multiple physical lines if long.
        joined = ", ".join(self.model.line)
        decl = f"{name}: line=({joined});"
        if len(decl) <= self.line_width:
            lines.append(decl)
        else:
            indent = " " * (len(name) + len(": line=("))
            wrapped = self._wrap_csv(self.model.line, indent)
            lines.append(f"{name}: line=({wrapped});")
        lines.append(f"use, {name};")
        return "\n".join(lines)

    def _wrap_csv(self, items: List[str], indent: str) -> str:
        out_lines: List[str] = []
        current = ""
        for i, item in enumerate(items):
            piece = item + ("," if i < len(items) - 1 else "")
            candidate = (current + " " + piece).strip()
            if current and len(indent) + len(candidate) > self.line_width:
                out_lines.append(current)
                current = piece
            else:
                current = candidate
        if current:
            out_lines.append(current)
        return ("\n" + indent).join(out_lines)

    def _kv_command(self, keyword: str, mapping) -> str:
        items = [f"{k}={_format_value(v)}" for k, v in mapping.items()]
        if not items:
            return f"{keyword};"
        one_line = f"{keyword}, " + ", ".join(items) + ";"
        if len(one_line) <= self.line_width:
            return one_line
        indent = " " * (len(keyword) + 2)
        body = (",\n" + indent).join(items)
        return f"{keyword}, {body};"

    def _beam_block(self) -> str:
        return "! ---- beam ----\n" + self._kv_command("beam", self.model.beam)

    def _options_block(self) -> str:
        return "! ---- options ----\n" + self._kv_command("option", self.model.options)

    def _samplers_block(self) -> str:
        if not self.model.samplers:
            return ""
        lines = ["! ---- samplers ----"]
        for s in self.model.samplers:
            if s == "all":
                lines.append("sample, all;")
            else:
                lines.append(f"sample, range={s};")
        return "\n".join(lines)
